### ISSUE TITLE
Class not found when unmarshalling: com.perflyst.twire.model.ChannelInfo

### ISSUE THREAD

**Issue by SArsalanK** [twireapp/Twire#19]
`04-30 18:15:43.443 992-1835/? E/Parcel: Class not found when unmarshalling: com.perflyst.twire.model.ChannelInfo
    java.lang.ClassNotFoundException: com.perflyst.twire.model.ChannelInfo
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:308)
        at java.lang.Class.forName(Class.java:272)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2275)
        at android.os.Parcel.readParcelable(Parcel.java:2239)
        at android.os.Parcel.readValue(Parcel.java:2146)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
        at android.os.BaseBundle.unparcel(BaseBundle.java:221)
        at android.os.BaseBundle.getString(BaseBundle.java:918)
        at android.content.Intent.getStringExtra(Intent.java:4960)
        at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1462)
        at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1046)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4578)
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4477)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:144)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3010)
        at android.os.Binder.execTransact(Binder.java:446)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.perflyst.twire.model.ChannelInfo" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:308) 
        at java.lang.Class.forName(Class.java:272) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2275) 
        at android.os.Parcel.readParcelable(Parcel.java:2239) 
        at android.os.Parcel.readValue(Parcel.java:2146) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2479) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
        at android.os.BaseBundle.getString(BaseBundle.java:918) 
        at android.content.Intent.getStringExtra(Intent.java:4960) 
        at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1462) 
        at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1046) 
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4578) 
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4477) 
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:144) 
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3010) 
        at android.os.Binder.execTransact(Binder.java:446) 
    	Suppressed: java.lang.ClassNotFoundException: com.perflyst.twire.model.ChannelInfo
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 18 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
04-30 18:15:43.603 10166-10166/com.perflyst.twire.debug E/SensorManager: sensor or listener is null`

**Comment by samfundev** [comment]
There are no reproduction steps for this issue and so I'm going to close this.
