### ISSUE TITLE
Viewing followed streamers causes crash

### ISSUE THREAD

**Issue by LoneFenris** [twireapp/Twire#368]
In 2.10.3, I seem to be unable to view my followed streamers without crashing. The view appears to start loading but then kicks me back the previous view, and Android sometimes will pop up that the app keeps crashing. Android 12.

**Comment by samfundev** [comment]
I'm unable to reproduce this bug. No crash when going to "my follows" or watching a streamer that I'm following. Can you get a logfile from the crash?

**Comment by LoneFenris** [comment]
Here's the logged error:

`FATAL EXCEPTION: pool-2-thread-1
Process: com.perflyst.twire, PID: 4824
java.lang.NullPointerException: Attempt to invoke virtual method 'java.net.URL com.perflyst.twire.model.ChannelInfo.getLogoURL()' on a null object reference
	at com.perflyst.twire.model.ChannelInfo.lambda$refreshPreview$2(ChannelInfo.java:222)
	at com.perflyst.twire.model.ChannelInfo.$r8$lambda$DnYGV8Lckd74Ub6jimrHsM_LRsI(Unknown Source:0)
	at com.perflyst.twire.model.ChannelInfo$$ExternalSyntheticLambda4.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)`

**Comment by LoneFenris** [comment]
If I may offer a suspicion: If I recall, follows are not deleted from Twire when removed on your account as of the new API changes, right? This may be a result of a followed streamer's twitch account being deleted (or not existing anymore) and Twire not being able to handle that?

**Comment by samfundev** [comment]
Thanks for that error. I've added a check to prevent that exception from happening.

**Comment by LoneFenris** [comment]
Thanks. I'll keep an eye out for any other errors that might be the result of null channels/users too.
