### ISSUE TITLE
Failed to play stream

### ISSUE THREAD

**Issue by ShoofLLC** [twireapp/Twire#439]
**Describe the bug**
Looks like something changed (probably twitch) and now we can't view streams anymore.

**Smartphone (please complete the following information):**
 - Device: Sony Xperia
 - Android Version: Android 12
 - Twire Version: 2.10.8

**Comment by LoneFenris** [comment]
Was just coming to report this. Error is:

```
01-07 11:40:00.734  8922  8922 D StreamFragment: Fetching viewers
01-07 11:40:00.858  8922  9179 W System.err: org.json.JSONException: No value for total
01-07 11:40:00.862  8922  9179 W System.err: 	at org.json.JSONObject.get(JSONObject.java:398)
01-07 11:40:00.862  8922  9179 W System.err: 	at org.json.JSONObject.getInt(JSONObject.java:487)
01-07 11:40:00.862  8922  9179 W System.err: 	at com.perflyst.twire.model.ChannelInfo.fetchFollowers(ChannelInfo.java:172)
01-07 11:40:00.862  8922  9179 W System.err: 	at com.perflyst.twire.model.ChannelInfo.lambda$getFollowers$1(ChannelInfo.java:157)
01-07 11:40:00.862  8922  9179 W System.err: 	at com.perflyst.twire.model.ChannelInfo.$r8$lambda$08zhm2Ht2352skUfxwvq_xbk8Nk(ChannelInfo.java:0)
01-07 11:40:00.862  8922  9179 W System.err: 	at com.perflyst.twire.model.ChannelInfo$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
01-07 11:40:00.862  8922  9179 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
01-07 11:40:00.862  8922  9179 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
01-07 11:40:00.862  8922  9179 W System.err: 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by blueyshark** [comment]
Same here for me, unfortunately. Android 14, latest version of Twire.

**Comment by ibinshoid** [comment]
Here too.
Android 10
twire 2.10.8

**Comment by YohannGutej** [comment]
I encountered the issue multiple times already, it seems the twitch api has some strange behaviour when fetching the stream info.
I also had troubles to play streams a few days ago but today it's working.
Thanks for the input @LoneFenris, it should be easy to add a fallback in case of missing non-video related information.

**Comment by samfundev** [comment]
It seems like twitch is doing something because I am having this error intermittently as well. Once the error happens again I'll look into this. I suspect this is related to https://github.com/streamlink/streamlink/pull/5414.

Also apologizes I haven't been able to work on this project for a few months because I haven't been able to sit due to some extreme back pain. Things have been getting better recently and I am going to try to get out an update soon.

**Comment by FlareHeart** [comment]
I got stuck unable to watch a stream at all today due to this error no matter how many times I reloaded. I tracked it down to being related to the Proxies. Once I disabled the Proxy, streams worked fine again. Of course this also functionally disables the adblock, but that appears to be where the issue is, if you haven't found it yet.
