### ISSUE TITLE
Crashing Out of Streams

### ISSUE THREAD

**Issue by cbmiller2610** [twireapp/Twire#449]
Twire keeps crashing out of streams and returning to the stream list (in this case I had selected the stream from the "My Streams" list, and the crash goes back to that screen but does not reload the list until you refresh.

Android App Log

```
```
type: logcat
osVersion: google/shiba/shiba:14/AP2A.240705.005/2024080200:user/release-keys
packageName: com.perflyst.twire:533
buffers: main,system,crash,events,kernel
level: verbose

--------- beginning of crash
08-06 20:16:27.561 17564 17627 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
08-06 20:16:27.561 17564 17627 E AndroidRuntime: Process: com.perflyst.twire, PID: 17564
08-06 20:16:27.561 17564 17627 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
08-06 20:16:27.561 17564 17627 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
08-06 20:16:27.561 17564 17627 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
08-06 20:16:27.561 17564 17627 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
08-06 20:16:27.561 17564 17627 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
08-06 20:16:27.561 17564 17627 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
08-06 20:16:27.561 17564 17627 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
08-06 20:16:27.561 17564 17627 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
08-06 20:16:27.561 17564 17627 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
08-06 20:16:27.561 17564 17627 E AndroidRuntime: 	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
08-06 20:16:27.561 17564 17627 E AndroidRuntime: 	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
08-06 20:16:27.561 17564 17627 E AndroidRuntime: 	at org.json.JSONObject.<init>(JSONObject.java:168)
08-06 20:16:27.561 17564 17627 E AndroidRuntime: 	at org.json.JSONObject.<init>(JSONObject.java:185)
08-06 20:16:27.561 17564 17627 E AndroidRuntime: 	at com.perflyst.twire.tasks.GetStreamViewersTask.doInBackground(GetStreamViewersTask.java:35)
08-06 20:16:27.561 17564 17627 E AndroidRuntime: 	at com.perflyst.twire.tasks.GetStreamViewersTask.doInBackground(GetStreamViewersTask.java:17)
08-06 20:16:27.561 17564 17627 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
08-06 20:16:27.561 17564 17627 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
08-06 20:16:27.561 17564 17627 E AndroidRuntime: 	... 3 more
--------- beginning of events
08-06 20:24:50.651 18675 18675 I wm_on_top_resumed_lost_called: [Token=141386939,Component Name=com.perflyst.twire.activities.stream.LiveStreamActivity,Reason=topStateChangedWhenResumed]
08-06 20:24:50.690 18675 18675 I view_enqueue_input_event: [eventType=Motion - Cancel,action=com.perflyst.twire/com.perflyst.twire.activities.stream.LiveStreamActivity]
08-06 20:24:51.402 18675 18675 I wm_on_paused_called: [Token=141386939,Component Name=com.perflyst.twire.activities.stream.LiveStreamActivity,Reason=performPause,time=1ms]
08-06 20:24:51.429 18675 18675 I viewroot_draw_event: [window=VRI[LiveStreamActivity],event=reportDrawFinished seqId=0]
08-06 20:24:51.445 18675 18675 I viewroot_draw_event: [window=VRI[LiveStreamActivity],event=reportDrawFinished seqId=0]
08-06 20:24:51.915 18675 18675 I viewroot_draw_event: [window=VRI[LiveStreamActivity],event=reportDrawFinished seqId=3]
08-06 20:24:55.125 18675 18675 I viewroot_draw_event: [window=VRI[LiveStreamActivity],event=reportDrawFinished seqId=4]
08-06 20:24:55.135 18675 18675 I viewroot_draw_event: [window=VRI[LiveStreamActivity],event=reportDrawFinished seqId=4]
08-06 20:25:20.749 18675 18675 I viewroot_draw_event: [window=VRI[LiveStreamActivity],event=reportDrawFinished seqId=5]
08-06 20:25:34.549 18675 18675 I viewroot_draw_event: [window=VRI[LiveStreamActivity],event=reportDrawFinished seqId=7]
08-06 20:25:34.567 18675 18675 I viewroot_draw_event: [window=VRI[LiveStreamActivity],event=reportDrawFinished seqId=7]
08-06 20:25:35.038 18675 18675 I wm_on_resume_called: [Token=141386939,Component Name=com.perflyst.twire.activities.stream.LiveStreamActivity,Reason=RESUME_ACTIVITY,time=1ms]
08-06 20:25:35.038 18675 18675 I wm_on_top_resumed_gained_called: [Token=141386939,Component Name=com.perflyst.twire.activities.stream.LiveStreamActivity,Reason=topWhenResuming]
--------- switch to crash
08-06 20:27:43.123 18675 18761 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
08-06 20:27:43.123 18675 18761 E AndroidRuntime: Process: com.perflyst.twire, PID: 18675
08-06 20:27:43.123 18675 18761 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
08-06 20:27:43.123 18675 18761 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
08-06 20:27:43.123 18675 18761 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
08-06 20:27:43.123 18675 18761 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
08-06 20:27:43.123 18675 18761 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
08-06 20:27:43.123 18675 18761 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
08-06 20:27:43.123 18675 18761 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
08-06 20:27:43.123 18675 18761 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
08-06 20:27:43.123 18675 18761 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
08-06 20:27:43.123 18675 18761 E AndroidRuntime: 	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
08-06 20:27:43.123 18675 18761 E AndroidRuntime: 	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
08-06 20:27:43.123 18675 18761 E AndroidRuntime: 	at org.json.JSONObject.<init>(JSONObject.java:168)
08-06 20:27:43.123 18675 18761 E AndroidRuntime: 	at org.json.JSONObject.<init>(JSONObject.java:185)
08-06 20:27:43.123 18675 18761 E AndroidRuntime: 	at com.perflyst.twire.tasks.GetStreamViewersTask.doInBackground(GetStreamViewersTask.java:35)
08-06 20:27:43.123 18675 18761 E AndroidRuntime: 	at com.perflyst.twire.tasks.GetStreamViewersTask.doInBackground(GetStreamViewersTask.java:17)
08-06 20:27:43.123 18675 18761 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
08-06 20:27:43.123 18675 18761 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
08-06 20:27:43.123 18675 18761 E AndroidRuntime: 	... 3 more
--------- switch to events
08-06 20:27:43.154 18675 18675 I wm_on_top_resumed_lost_called: [Token=141386939,Component Name=com.perflyst.twire.activities.stream.LiveStreamActivity,Reason=topStateChangedWhenResumed]
08-06 20:27:43.488 19335 19335 I auditd  : avc=type=1400 audit(0.0:18401): avc:  denied  { read } for  comm="app_process64" name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=374 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.500 19335 19335 I auditd  : avc=type=1400 audit(0.0:18402): avc:  denied  { read } for  comm="app_process64" name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=374 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.504 19335 19335 I auditd  : avc=type=1400 audit(0.0:18403): avc:  denied  { read } for  comm=".perflyst.twire" name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=374 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.508 19335 19335 I auditd  : avc=type=1400 audit(0.0:18404): avc:  denied  { read } for  comm=".perflyst.twire" name="u:object_r:odsign_prop:s0" dev="tmpfs" ino=285 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:odsign_prop:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.508 19335 19335 I auditd  : avc=type=1400 audit(0.0:18405): avc:  denied  { read } for  comm=".perflyst.twire" name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=374 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.508 19335 19335 I auditd  : avc=type=1400 audit(0.0:18406): avc:  denied  { getattr } for  comm=".perflyst.twire" path="/apex/apex-info-list.xml" dev="tmpfs" ino=83 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:apex_info_file:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.528 19335 19335 I auditd  : avc=type=1400 audit(0.0:18407): avc:  denied  { lock } for  comm=".perflyst.twire" path="/system/framework/arm64/boot.art" dev="dm-12" ino=1336 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.532 19335 19335 I auditd  : avc=type=1400 audit(0.0:18408): avc:  denied  { lock } for  comm=".perflyst.twire" path="/system/framework/arm64/boot-core-libart.art" dev="dm-12" ino=1270 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.532 19335 19335 I auditd  : avc=type=1400 audit(0.0:18409): avc:  denied  { lock } for  comm=".perflyst.twire" path="/system/framework/arm64/boot-okhttp.art" dev="dm-12" ino=1318 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.532 19335 19335 I auditd  : avc=type=1400 audit(0.0:18410): avc:  denied  { lock } for  comm=".perflyst.twire" path="/system/framework/arm64/boot-bouncycastle.art" dev="dm-12" ino=1258 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.532 19335 19335 I auditd  : avc=type=1400 audit(0.0:18411): avc:  denied  { lock } for  comm=".perflyst.twire" path="/system/framework/arm64/boot-apache-xml.art" dev="dm-12" ino=1252 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.532 19335 19335 I auditd  : avc=type=1400 audit(0.0:18412): avc:  denied  { lock } for  comm=".perflyst.twire" path="/system/framework/arm64/boot-framework.art" dev="dm-12" ino=1306 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.540 19335 19335 I auditd  : avc=type=1400 audit(0.0:18413): avc:  denied  { lock } for  comm=".perflyst.twire" path="/system/framework/arm64/boot-framework-graphics.art" dev="dm-12" ino=1288 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.540 19335 19335 I auditd  : avc=type=1400 audit(0.0:18414): avc:  denied  { lock } for  comm=".perflyst.twire" path="/system/framework/arm64/boot-framework-location.art" dev="dm-12" ino=1294 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.540 19335 19335 I auditd  : avc=type=1400 audit(0.0:18415): avc:  denied  { lock } for  comm=".perflyst.twire" path="/system/framework/arm64/boot-ext.art" dev="dm-12" ino=1276 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.540 19335 19335 I auditd  : avc=type=1400 audit(0.0:18416): avc:  denied  { lock } for  comm=".perflyst.twire" path="/system/framework/arm64/boot-telephony-common.art" dev="dm-12" ino=1324 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.544 19335 19335 I auditd  : avc=type=1400 audit(0.0:18417): avc:  denied  { lock } for  comm=".perflyst.twire" path="/system/framework/arm64/boot-voip-common.art" dev="dm-12" ino=1330 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.544 19335 19335 I auditd  : avc=type=1400 audit(0.0:18418): avc:  denied  { lock } for  comm=".perflyst.twire" path="/system/framework/arm64/boot-ims-common.art" dev="dm-12" ino=1312 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.544 19335 19335 I auditd  : avc=type=1400 audit(0.0:18419): avc:  denied  { lock } for  comm=".perflyst.twire" path="/system/framework/arm64/boot-framework-nfc.art" dev="dm-12" ino=1300 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.544 19335 19335 I auditd  : avc=type=1400 audit(0.0:18420): avc:  denied  { lock } for  comm=".perflyst.twire" path="/system/framework/arm64/boot-core-icu4j.art" dev="dm-12" ino=1264 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.548 19335 19335 I auditd  : avc=type=1400 audit(0.0:18421): avc:  denied  { lock } for  comm=".perflyst.twire" path="/system/framework/arm64/boot-framework-adservices.art" dev="dm-12" ino=1282 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.608 19335 19335 I auditd  : avc=type=1400 audit(0.0:18422): avc:  denied  { read } for  comm="main" name="u:object_r:build_attestation_prop:s0" dev="tmpfs" ino=111 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:build_attestation_prop:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.608 19335 19335 I auditd  : avc=type=1400 audit(0.0:18423): avc:  denied  { read } for  comm="main" name="u:object_r:build_attestation_prop:s0" dev="tmpfs" ino=111 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:build_attestation_prop:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.608 19335 19335 I auditd  : avc=type=1400 audit(0.0:18424): avc:  denied  { read } for  comm="main" name="u:object_r:build_attestation_prop:s0" dev="tmpfs" ino=111 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:build_attestation_prop:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.608 19335 19335 I auditd  : avc=type=1400 audit(0.0:18425): avc:  denied  { read } for  comm="main" name="u:object_r:build_attestation_prop:s0" dev="tmpfs" ino=111 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:build_attestation_prop:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.608 19335 19335 I auditd  : avc=type=1400 audit(0.0:18426): avc:  denied  { read } for  comm="main" name="u:object_r:build_attestation_prop:s0" dev="tmpfs" ino=111 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:build_attestation_prop:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.608 19335 19335 I auditd  : avc=type=1400 audit(0.0:18427): avc:  denied  { read } for  comm="main" name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=374 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.636 19335 19335 I auditd  : avc=type=1400 audit(0.0:18428): avc:  denied  { read } for  comm="binder:19335_1" name="u:object_r:qemu_sf_lcd_density_prop:s0" dev="tmpfs" ino=308 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:qemu_sf_lcd_density_prop:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.636 19335 19335 I auditd  : avc=type=1400 audit(0.0:18429): avc:  denied  { read } for  comm="binder:19335_1" name="u:object_r:qemu_sf_lcd_density_prop:s0" dev="tmpfs" ino=308 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:qemu_sf_lcd_density_prop:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.708 19335 19335 I auditd  : avc=type=1400 audit(0.0:18430): avc:  denied  { read } for  comm=".perflyst.twire" name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=374 scontext=u:r:untrusted_app:s0:c160,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=com.perflyst.twire
08-06 20:27:43.765 19335 19335 I wm_on_create_called: [Token=266926231,Component Name=com.perflyst.twire.activities.main.MyStreamsActivity,Reason=performCreate,time=60ms]
08-06 20:27:43.767 19335 19335 I wm_on_start_called: [Token=266926231,Component Name=com.perflyst.twire.activities.main.MyStreamsActivity,Reason=handleStartActivity,time=0ms]
08-06 20:27:43.770 19335 19335 I wm_on_resume_called: [Token=266926231,Component Name=com.perflyst.twire.activities.main.MyStreamsActivity,Reason=RESUME_ACTIVITY,time=0ms]
08-06 20:27:43.787 19335 19335 I wm_on_top_resumed_gained_called: [Token=266926231,Component Name=com.perflyst.twire.activities.main.MyStreamsActivity,Reason=topStateChangedWhenResumed]
08-06 20:27:43.851 19335 19335 I viewroot_draw_event: [window=VRI[MyStreamsActivity],event=reportDrawFinished seqId=0]
08-06 20:27:47.637 19335 19335 I wm_on_top_resumed_lost_called: [Token=266926231,Component Name=com.perflyst.twire.activities.main.MyStreamsActivity,Reason=topStateChangedWhenResumed]
08-06 20:27:47.706 19335 19335 I view_enqueue_input_event: [eventType=Motion - Cancel,action=com.perflyst.twire/com.perflyst.twire.activities.main.MyStreamsActivity]
08-06 20:27:49.484 19335 19335 I wm_on_paused_called: [Token=266926231,Component Name=com.perflyst.twire.activities.main.MyStreamsActivity,Reason=performPause,time=1ms]
08-06 20:27:49.510 19335 19335 I viewroot_draw_event: [window=VRI[MyStreamsActivity],event=Not drawing due to not visible]
08-06 20:27:49.513 19335 19335 I wm_on_stop_called: [Token=266926231,Component Name=com.perflyst.twire.activities.main.MyStreamsActivity,Reason=STOP_ACTIVITY_ITEM,time=1ms]
08-06 20:37:45.436 19335 19335 I wm_on_restart_called: [Token=266926231,Component Name=com.perflyst.twire.activities.main.MyStreamsActivity,Reason=performRestart,time=0ms]
08-06 20:37:45.449 19335 19335 I wm_on_start_called: [Token=266926231,Component Name=com.perflyst.twire.activities.main.MyStreamsActivity,Reason=handleStartActivity,time=13ms]
08-06 20:37:45.452 19335 19335 I wm_on_resume_called: [Token=266926231,Component Name=com.perflyst.twire.activities.main.MyStreamsActivity,Reason=RESUME_ACTIVITY,time=1ms]
08-06 20:37:45.453 19335 19335 I wm_on_top_resumed_gained_called: [Token=266926231,Component Name=com.perflyst.twire.activities.main.MyStreamsActivity,Reason=topWhenResuming]
08-06 20:37:45.462 19335 19335 I viewroot_draw_event: [window=VRI[MyStreamsActivity],event=Start draw after previous draw not visible]
08-06 20:37:45.543 19335 19335 I viewroot_draw_event: [window=VRI[MyStreamsActivity],event=reportDrawFinished seqId=0]
08-06 20:37:57.185 19335 19335 I wm_on_top_resumed_lost_called: [Token=266926231,Component Name=com.perflyst.twire.activities.main.MyStreamsActivity,Reason=topStateChangedWhenResumed]
08-06 20:37:57.218 19335 19335 I view_enqueue_input_event: [eventType=Motion - Cancel,action=com.perflyst.twire/com.perflyst.twire.activities.main.MyStreamsActivity]
08-06 20:37:58.587 19335 19335 I wm_on_paused_called: [Token=266926231,Component Name=com.perflyst.twire.activities.main.MyStreamsActivity,Reason=performPause,time=0ms]
--------- beginning of main
08-06 20:37:58.980 19335 19335 D VRI[MyStreamsActivity]: visibilityChanged oldVisibility=true newVisibility=false
--------- switch to events
08-06 20:37:59.009 19335 19335 I viewroot_draw_event: [window=VRI[MyStreamsActivity],event=Not drawing due to not visible]
08-06 20:37:59.022 19335 19335 I wm_on_stop_called: [Token=266926231,Component Name=com.perflyst.twire.activities.main.MyStreamsActivity,Reason=STOP_ACTIVITY_ITEM,time=2ms]
```

```

**Comment by Oktayey** [comment]
Does this happen shortly after using the chat field? In my experience, the stream only crashes up to a minute or so after writing a chat message or perhaps even opening the chat message field.

**Comment by Te-M** [comment]
Same problem, noticed it after chat, tried switching keyboard just in case but didn't help.  I also noticed a problem with typing I think it was the ':' character, seemed to exit out.  Didn't seem to be listing emotes (or at least all of them) either.

**Comment by FlareHeart** [comment]
Typing anything causes an instant crash for me. No delay, just instant crash. No emotes just basic text.

**Comment by darkph0rze** [comment]
For me it crashes as soon as the "Connecting to chat" is established. Don't even have time to type anything :D (2.12.1). Ironically I updated the version from 2.10 because the stream stopped sometimes but at least that version never crashed and chat functioned fine.
